% ANOVA: do stats

data = load('dichotic_data.mat'); % load n subj x 16 conditon data

conditions1 = {...
    'ndea_left';... 
    'ndea_right';...
    'nhum_left';... 
    'nhum_right';...
    'nani_left';... 
    'nani_right';...
    'nenv_left';... 
    'nenv_right';...
    'next_left';... 
    'next_right';...
    'nmus_left';... 
    'nmus_right';...
    'npin_left';... 
    'npin_right';...
    'nsil_left';... 
    'nsil_right';...
    };

conditions2 = {...
    'ndea','left';... 
    'ndea','right';...
    'nhum','left';... 
    'nhum','right';...
    'nani','left';... 
    'nani','right';...
    'nenv','left';... 
    'nenv','right';...
    'next','left';... 
    'next','right';...
    'nmus','left';... 
    'nmus','right';...
    'npin','left';... 
    'npin','right';...
    'nsil','left';... 
    'nsil','right';...
    };

% reaction time
data    = array2table(data,'VariableNames',conditions1);
within  = cell2table(conditions2,...
    'VariableNames',{'sound','laterality'});
model   = fitrm(data,'ndea_left-nsil_right~1','WithinDesign',within);
spheric = mauchly(model) % Mauchly test for sphericity
epscorr = epsilon(model) % epsilon correction
results = ranova(model,'WithinModel','sound*laterality')
multcompare(model,'sound')
multcompare(model,'laterality')
multcompare(model,'sound','By','laterality')
multcompare(model,'laterality','By','sound')

% accuracy
data    = array2table(data,'VariableNames',conditions1);
within  = cell2table(conditions2,...
    'VariableNames',{'sound','laterality'});
model   = fitrm(data,'ndea_left-nsil_right~1','WithinDesign',within);
spheric = mauchly(model) % Mauchly test for sphericity
epscorr = epsilon(model) % epsilon correction
results = ranova(model,'WithinModel','sound*laterality')
multcompare(model,'sound')
multcompare(model,'laterality')
multcompare(model,'sound','By','laterality')
multcompare(model,'laterality','By','sound')

